apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: quarked
spec:
  runLatest:
    configuration:
      revisionTemplate:
        metadata:
          annotations:
            autoscaling.knative.dev/target: "10"      
        spec:
          container:
            image: docker.io/burrsutter/quarked:1.0.2
            resources:
              requests: 
                memory: "50Mi" 
                cpu: "75m" 
              limits:
                memory: "50Mi"
                cpu: "75m" 
            livenessProbe:
              httpGet:
                path: /healthz
            readinessProbe:
              httpGet:
                path: /healthz