apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: gonow
spec:
  runLatest:
    configuration:
      revisionTemplate:
        metadata:
          annotations:
            autoscaling.knative.dev/target: "10"      
        spec:
          container:
            image: docker.io/burrsutter/gonow:1.0.0
            livenessProbe:
              httpGet:
                path: /healthz
            readinessProbe:
              httpGet:
                path: /healthz