apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pythoned
spec:
  template:
    metadata:
      annotations:        
        autoscaling.knative.dev/target: "10"
        autoscaling.knative.dev/window: 16s            
    spec:
      containers:
      - image: docker.io/burrsutter/pythoned:1.0.0
        resources:
          requests: 
            memory: "30Mi" 
            cpu: "75m" 
          limits:
            memory: "30Mi"
            cpu: "75m" 
        readinessProbe:
          httpGet:
            path: /healthz
