apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: booted
spec:
  template:
    metadata:
      annotations:        
        autoscaling.knative.dev/target: "10"
        autoscaling.knative.dev/window: 16s            
    spec:
      containers:
      - image: docker.io/burrsutter/booted:2.0.0
        resources:
          requests: 
            memory: "150Mi" 
            cpu: "500m" 
          limits:
            memory: "150Mi"
            cpu: "500m" 
        readinessProbe:
          httpGet:
            path: /healthz