apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: noded
spec:
  runLatest:
    configuration:
      revisionTemplate:
        metadata:
          annotations:
            autoscaling.knative.dev/target: "10"
        spec:
          container:
            image: docker.io/burrsutter/noded:1.0.1
            resources:
              requests: 
                memory: "55Mi" 
                cpu: "75m" 
              limits:
                memory: "55Mi"
                cpu: "75m" 
#            livenessProbe:
#              httpGet:
#                path: /healthz
            readinessProbe:
              httpGet:
                path: /healthz